In [3]:
import pandas as pd

BASE = r'C:\Users\arthur.oliveira\OneDrive\Study\Python-Data-Science\Introduction to Data Science in Python - Michigan\Databases\apple_quality.csv'

In [10]:
df = pd.read_csv(BASE, index_col=0)

In [11]:
df.head()

,Size,Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
A_id,,,,,,,,
0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good

In [12]:
df.columns

Index(['Size ', 'Weight ', 'Sweetness', 'Crunchiness', 'Juiciness', 'Ripeness',
       'Acidity', 'Quality'],
      dtype='object')

In [14]:
# Removing spaces from column title
new_df = df.rename(mapper=str.strip, axis='columns')

In [16]:
new_df.columns

Index(['Size', 'Weight', 'Sweetness', 'Crunchiness', 'Juiciness', 'Ripeness',
       'Acidity', 'Quality'],
      dtype='object')

In [18]:
# Renaming 
new_df = new_df.rename(columns={'Size':'Apple Size','Weight': 'Apple Weight'})

In [19]:
new_df

,Apple Size,Apple Weight,Sweetness,Crunchiness,Juiciness,Ripeness,Acidity,Quality
A_id,,,,,,,,
0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...
3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [21]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4001 entries, 0.0 to nan
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Apple Size    4000 non-null   float64
 1   Apple Weight  4000 non-null   float64
 2   Sweetness     4000 non-null   float64
 3   Crunchiness   4000 non-null   float64
 4   Juiciness     4000 non-null   float64
 5   Ripeness      4000 non-null   float64
 6   Acidity       4001 non-null   object
 7   Quality       4000 non-null   object
dtypes: float64(6), object(2)
memory usage: 281.3+ KB

In [22]:
# CONVERTING COLUMN TITLE TO LOWER CASE USING LIST COMPREHENSION
cols = list(new_df.columns)
cols = [x.lower().strip() for x in cols]
new_df.columns=cols
new_df.columns

Index(['apple size', 'apple weight', 'sweetness', 'crunchiness', 'juiciness',
       'ripeness', 'acidity', 'quality'],
      dtype='object')

In [23]:
new_df

,apple size,apple weight,sweetness,crunchiness,juiciness,ripeness,acidity,quality
A_id,,,,,,,,
0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...
3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good
NaN,NaN,NaN,NaN,NaN,NaN,NaN,Created_by_Nidula_Elgiriyewithana,NaN

In [26]:
new_df.dropna()

,apple size,apple weight,sweetness,crunchiness,juiciness,ripeness,acidity,quality
A_id,,,,,,,,
0.0,-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590483,good
1.0,-1.195217,-2.839257,3.664059,1.588232,0.853286,0.867530,-0.722809367,good
2.0,-0.292024,-1.351282,-1.738429,-0.342616,2.838636,-0.038033,2.621636473,bad
3.0,-0.657196,-2.271627,1.324874,-0.097875,3.637970,-3.413761,0.790723217,good
4.0,1.364217,-1.296612,-0.384658,-0.553006,3.030874,-1.303849,0.501984036,good
...,...,...,...,...,...,...,...,...
3995.0,0.059386,-1.067408,-3.714549,0.473052,1.697986,2.244055,0.137784369,bad
3996.0,-0.293118,1.949253,-0.204020,-0.640196,0.024523,-1.087900,1.854235285,good
3997.0,-2.634515,-2.138247,-2.440461,0.657223,2.199709,4.763859,-1.334611391,bad
3998.0,-4.008004,-1.779337,2.366397,-0.200329,2.161435,0.214488,-2.229719806,good
3999.0,0.278540,-1.715505,0.121217,-1.154075,1.266677,-0.776571,1.599796456,good

In [27]:
new_df.describe()

,apple size,apple weight,sweetness,crunchiness,juiciness,ripeness
count,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000,4000.000000
mean,-0.503015,-0.989547,-0.470479,0.985478,0.512118,0.498277
std,1.928059,1.602507,1.943441,1.402757,1.930286,1.874427
min,-7.151703,-7.149848,-6.894485,-6.055058,-5.961897,-5.864599
25%,-1.816765,-2.011770,-1.738425,0.062764,-0.801286,-0.771677
50%,-0.513703,-0.984736,-0.504758,0.998249,0.534219,0.503445
75%,0.805526,0.030976,0.801922,1.894234,1.835976,1.766212
max,6.406367,5.790714,6.374916,7.619852,7.364403,7.237837

In [30]:
# querying df
new_df[new_df['apple size']>0].describe()

,apple size,apple weight,sweetness,crunchiness,juiciness,ripeness
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,1.372769,-1.273119,-1.063861,1.217828,0.474103,0.197451
std,1.055585,1.693028,1.814040,1.560799,2.077054,1.792362
min,0.000030,-7.149848,-6.507847,-4.495359,-5.814308,-5.864599
25%,0.539131,-2.368192,-2.287206,0.225953,-0.971885,-1.059185
50%,1.158013,-1.222490,-1.078912,1.260178,0.463743,0.104660
75%,1.972731,-0.159907,0.057403,2.245172,1.873304,1.433606
max,6.406367,4.363066,4.717131,7.619852,7.364403,6.134522

In [32]:
# Multiple queries & and - | or 
new_df[(new_df['apple size'] >0) & (new_df['apple weight']>0)].describe()

,apple size,apple weight,sweetness,crunchiness,juiciness,ripeness
count,365.000000,365.000000,365.000000,365.000000,365.000000,365.000000
mean,1.326143,0.911807,-1.162538,1.069202,0.201333,-0.498019
std,1.066969,0.791204,1.469081,1.686199,1.905664,1.581422
min,0.000306,0.001743,-5.118948,-4.495359,-5.261636,-5.864599
25%,0.507344,0.321167,-2.185413,0.037369,-1.166639,-1.578244
50%,1.106746,0.716845,-1.185189,1.055575,0.178083,-0.574947
75%,1.847878,1.287747,-0.244111,2.248843,1.432184,0.629369
max,5.866232,4.363066,3.014961,6.724931,5.452809,3.719801